language: android
sudo: false
jdk: oraclejdk7
env:
  matrix:
  - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a armeabi
android:
  components:
  - platform-tools
  - build-tools-21.1.1
  - android-L
  - extra
before_install:
#please use travis to config your sign
before_script:
- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
- emulator -avd test -no-skin -no-audio -no-window &
- adb wait-for-device
- adb shell input keyevent 82 &
script:
- ./gradlew assembleRelease
deploy:
  provider: releases
  #api_key:please use travis to config api key to upload release
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true
